collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.08458646
color:
  saturation: 0.4465051
  brandStrength: 0.2806656
  rhythmicContrast: 0.6878152
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.8984898
layout_spectrum: 0.8320802
name: jamesonthego
